"""add incident_id to audit_logs

Revision ID: bce7ac2167ea
Revises: 43b79a424fe2
Create Date: 2026-09-04 14:15:28.173090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce7ac2167ea'
down_revision: Union[str, Sequence[str], None] = '43b79a424fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('incident_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_incident_id'), 'audit_logs', ['incident_id'], unique=False)
    op.create_foreign_key(
        'fk_audit_logs_incident_id_incidents', 'audit_logs', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_audit_logs_incident_id_incidents', 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_incident_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'incident_id')
    # ### end Alembic commands ###
